version: '3.8'

services:
  flask-ai:
    build: ./flask-ai
    env_file:
      - ./flask-ai/.env
    ports:
      - "5001:5001"  
    restart: always
    depends_on:
      - mongodb
    # Optional resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000" 
    depends_on:
      - flask-ai
      - mongodb
    restart: always

  client:
    build: ./client  
    depends_on:
      - server
      - flask-ai
    restart: always

  mongodb:
    image: mongo
    container_name: mongo
    command: ["--quiet"]
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
