services:
  flask-ai:
    build: ./flask-ai
    ports:
      - "5001:5001"
    restart: always

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - flask-ai
    restart: always  

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
      - flask-ai
    restart: always

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    command: ["--quiet"]
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
