version: '3.8'

services:
  flask-ai:
    build: ./flask-ai
    env_file:
      - ./flask-ai/.env
    restart: always
    depends_on:
      - mongodb
    # Optional resource limits
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M

  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - flask-ai
      - mongodb
    restart: always

  client:
    build: ./client
    ports:
      - "80:80"  # React via Nginx
    depends_on:
      - server
      - flask-ai
    restart: always

  mongodb:
    image: mongo
    container_name: mongo
    command: ["--quiet"]
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
